# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


impute_with_colmean <- function(X) {
    .Call(`_GMMHC_impute_with_colmean`, X)
}

calculate_paras_with_class <- function(X, class0) {
    .Call(`_GMMHC_calculate_paras_with_class`, X, class0)
}

solvegmm <- function(X, para_0, max_iter, epsilon_dif = 0.000001, epsilon_var = 0.00000001) {
    .Call(`_GMMHC_myalgorithm`, X, para_0, max_iter, epsilon_dif, epsilon_var)
}

init_para_kmeans <- function(X, K){
  i <- 1
  while (i<=10){
    if_ok <- TRUE
    X0 <- impute_with_colmean(X)
    class0 <- kmeans(X0,K)$cluster   # kmeans????
    para_init <- calculate_paras_with_class(X0, class0)
    for(k in 1:K){
      if (det(para_init$sig2[[k]])<=0){
        i <- i+1
        if_ok <- FALSE
      }
    }
    if (if_ok) return(list(X0 = X0,class0=class0, para_init=para_init))
    if (i>10) print("fail to achieve positive definite covariance")
  }

}

GMMHC <- function(X_array, ks, min.nc=2, max.nc=15, maxiter = 100, 
                  distance = "euclidean", method="average",index_nb = "kl"){
  library(NbClust)
  epsilon_dif= 1e-6
  d <- dim(X_array)[3]
  for (i in 1:d){
    output <- list()
    index <- array(dim=length(ks))
    for (j in 1:length(ks)){
      para_init <- init_para_kmeans(X_array[,,i], ks[j])$para_init
      output[[j]] <- solvegmm(X_array[,,i],para_init,maxiter, epsilon_dif)
      index[j] <- output[[j]]$index_Vk
    }
    j_best <- which.min(index)
    if (i==1){
      w_cbind <- output[[j_best]]$w[,-1]
    }else{
      w_cbind <- cbind(w_cbind,output[[j_best]]$w[,-1])
    }
  }
  w_clus_average <- NbClust(w_cbind,distance = distance, min.nc = min.nc, max.nc = max.nc,
                            method=method,index = index_nb)
  best_num <- w_clus_average$Best.nc
  class_est <- w_clus_average$Best.partition
  return(list(best_num=best_num, class_est=class_est))
}

